### ISSUE TITLE
[BUG]: Unable to Open Dashboard-PowerPlatformAdminDashboard_2020-09-19 to configure

### ISSUE THREAD

**Issue by ruenells** [microsoft/powerapps-tools#511]
**Describe the bug**
Feedback Type:
Frown (Error)

Timestamp:
2020-10-09T21:46:53.0564281Z

Local Time:
2020-10-09T15:46:53.0564281-06:00

Session ID:
67e1ef85-07c1-4d43-a176-cac746b93b0b

Release:
January 2020

Product Version:
2.76.5678.1521 (19.12) (x64)

Error Message:
Unrecognized JSON property: sourceQueryCulture. Check path 'model.sourceQueryCulture', line 15, position 26.

Stack Trace:
   at Microsoft.AnalysisServices.Tabular.MetadataObject.DeserializeFromJsonObject(JObject jsonObj, DeserializeOptions options, Int32 dbCompatibilityLevel)
   at Microsoft.AnalysisServices.Tabular.Database.ReadPropertyFromJson(JProperty jsonProp, DeserializeOptions options)
   at Microsoft.AnalysisServices.Tabular.Database.DeserializeFromJsonObject(JObject jsonObj, DeserializeOptions options)
   at Microsoft.AnalysisServices.Tabular.JsonSerializer.DeserializeDatabase(String json, DeserializeOptions options)
   at Microsoft.PowerBI.Client.Windows.AnalysisServices.AnalysisServicesService.CreateDatabase(String schemaJson)
   at Microsoft.PowerBI.Client.Windows.Services.ReportFactory.CreateLocalDatabase(IPowerBIPackage powerBIPackage, String pbixFilePath, PowerBIPackageOpenOptions options, IAnalysisServicesService analysisServices)

Stack Trace Message:
Unrecognized JSON property: sourceQueryCulture. Check path 'model.sourceQueryCulture', line 15, position 26.

Invocation Stack Trace:
   at Microsoft.Mashup.Host.Document.ExceptionExtensions.GetCurrentInvocationStackTrace()
   at Microsoft.Mashup.Client.UI.Shared.FeedbackErrorInfo..ctor(String message, Exception exception, Nullable`1 stackTraceInfo, String messageDetail)
   at Microsoft.PowerBI.Client.Windows.Services.TemplateManager.TryImportTemplate(IPowerBIWindowService windowService, IQueryServices queryServices, IExceptionHandler exceptionHandler, TelemetryUserActionId entryPoint, Boolean& editQueries, String filePath)
   at Microsoft.PowerBI.Client.Windows.Commands.ApplicationCommands.DataImportCommands.ImportTemplate(IPowerBIWindowService windowService, IExceptionHandler exceptionHandler, ImportTemplateParameters parameters)
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.Practices.Prism.Commands.DelegateCommandBase.<>c__DisplayClass4_0.<.ctor>b__0(Object arg)
   at Microsoft.Practices.Prism.Commands.DelegateCommandBase.<Execute>d__10.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Practices.Prism.Commands.DelegateCommandBase.Execute(Object parameter)
   at Microsoft.Practices.Prism.Commands.DelegateCommand`1.<Execute>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Practices.Prism.Commands.DelegateCommand`1.Execute(T parameter)
   at Microsoft.PowerBI.Client.Windows.Commands.CompositeCommand`1.Execute(ICommand command, Object parameter)
   at Microsoft.Practices.Prism.Commands.CompositeCommand.Execute(Object parameter)
   at Microsoft.PowerBI.Client.Windows.Commands.CompositeCommand`1.Execute(T parameter)
   at Microsoft.PowerBI.Client.Windows.MainWindow.OpenDocument(TelemetryUserActionId entryPoint, String testFilePath)
   at Microsoft.Mashup.Client.UI.Shared.UICommands.CommandActionHandlerBase.CommandAction(UInt32 commandId)
   at Microsoft.Mashup.Client.UI.Windows.Ribbon.RibbonCommandHandler.Execute(UInt32 commandId, CommandExecutionVerb verb, PropertyKeyRef keyRef, PropVariantRef currentValue, IUISimplePropertySet commandExecutionProperties)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at Microsoft.Mashup.Client.UI.Shared.WebDialogs.WebDialog.<>n__0(IWindowHandle owner)
   at Microsoft.Mashup.Client.UI.Shared.WindowManager.ShowModal[T](T dialog, Func`1 showModalFunction)
   at Microsoft.PowerBI.Client.Program.<>c__DisplayClass2_0.<Main>b__1()
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<>c__DisplayClass3_0.<HandleExceptionsWithNestedTasks>b__0()
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.PowerBI.Client.Program.Main(String[] args)

OS Version:
Microsoft Windows NT 10.0.18362.0 (x64 en-US)

CLR Version:
4.7 or later [Release Number = 528040]

Peak Virtual Memory:
38.3 GB

Private Memory:
436 MB

Peak Working Set:
593 MB

IE Version:
11.1082.18362.0

User ID:
ebfeada7-e04e-4495-9c00-e2ddf5d46504

Workbook Package Info:
1* - en-US, Query Groups: 0, fastCombine: Disabled, runBackgroundAnalysis: True.

Telemetry Enabled:
True

Snapshot Trace Logs:
C:\Users\dreyes\AppData\Local\Microsoft\Power BI Desktop SSRS\FrownSnapShot633369225.zip

Model Default Mode:
Empty

Performance Trace Logs:
C:\Users\dreyes\AppData\Local\Microsoft\Power BI Desktop SSRS\PerformanceTraces.zip

Disabled Preview Features:
PBI_shapeMapVisualEnabled
PBI_SpanishLinguisticsEnabled
PBI_NewWebTableInference
PBI_showIncrementalRefreshPolicy
PBI_qnaLiveConnect
PQ_AIInsightsFunctionBrowser
PBI_realTimeRefresh
PBI_QueryDiagnostics
PBI_showMinervaRibbon
PBI_showMinervaViewNavigator
PBI_decompositionTree
PBI_themeDialog

Disabled DirectQuery Options:
TreatHanaAsRelationalSource

Cloud:
GlobalCloud

DPI Scale:
150%

Supported Services:
Power BI Report Server,  Power BI

**Comment by manuelap-msft** [comment]
Hello,

it sounds like you're on an older version of Power BI Desktop - could you upgrade to the latest available version and try again? You're looking for the October 2020 release.
![image](https://user-images.githubusercontent.com/55705669/95737116-18b7a300-0c7f-11eb-988a-4b6888a95032.png)

Thanks for using CoE!

**Comment by manuelap-msft** [comment]
Closing old issues with no action
