### ISSUE TITLE
[BUG]: Can't load Power Platform Center of Excellence Starter Kit Dashboard

### ISSUE THREAD

**Issue by kcarr00** [microsoft/powerapps-tools#524]
There is a dashboard that comes with the Power Platform Center of Excellence Starter Kit and getting the following error message trying to open it in the Power BI desktop. Colleague is also getting the same error when following the same steps:

Something went wrong

Failed to save modifications to the server.  Error returned: 'Expression in partition 'n/a' in table 'n/a' references an unknown entity.'.
Dashboard-PowerPlatformAdminDashboard_2020-09-19

Double click on the Dashboard-PowerPlatformAdminDashboard_2020-09-19.pbit file that comes with the Power Platform Center of Excellence Starter Kit

**Expected behavior**
Dashboard would prompt to enter the URL of the COE site and then fully load the dashboard

**Screenshots**

![image](https://user-images.githubusercontent.com/71848708/96036373-fada7180-0e29-11eb-98e9-2f3f17d9689e.png)

**Additional context**
Feedback Type:
Frown (Error)

Error Message:
Failed to save modifications to the server. Error returned: 'Expression in partition 'n/a' in table 'n/a' references an unknown entity.
'.

Stack Trace:
   at Microsoft.PowerBI.Client.Windows.Storage.FileOpenError.HandleError(IWindowService windowService, LocalizedString title)
   at Microsoft.PowerBI.Client.Windows.Services.TemplateManager.TryImportTemplate(IPowerBIWindowService windowService, IQueryServices queryServices, IExceptionHandler exceptionHandler, TelemetryUserActionId entryPoint, Boolean& editQueries, String filePath)
   at Microsoft.PowerBI.Client.Windows.Commands.ApplicationCommands.DataImportCommands.ImportTemplate(IPowerBIWindowService windowService, IExceptionHandler exceptionHandler, ImportTemplateParameters parameters)
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)

Stack Trace Message:
Failed to save modifications to the server. Error returned: 'Expression in partition 'n/a' in table 'n/a' references an unknown entity.
'.

Invocation Stack Trace:
   at Microsoft.Mashup.Host.Document.ExceptionExtensions.GetCurrentInvocationStackTrace()
   at Microsoft.Mashup.Client.UI.Shared.StackTraceInfo..ctor(String exceptionStackTrace, String invocationStackTrace, String exceptionMessage)
   at Microsoft.PowerBI.Client.Windows.Telemetry.PowerBIUserFeedbackServices.GetStackTraceInfo(Exception e)
   at Microsoft.PowerBI.Client.Windows.Telemetry.PowerBIUserFeedbackServices.ReportException(IWindowHandle activeWindow, IUIHost uiHost, FeedbackPackageInfo feedbackPackageInfo, Exception e, Boolean useGDICapture)
   at Microsoft.Mashup.Client.UI.Shared.UnexpectedExceptionHandler.<>c__DisplayClass14_0.<HandleException>b__0()
   at Microsoft.Mashup.Client.UI.Shared.UnexpectedExceptionHandler.HandleException(Exception e)
   at Microsoft.PowerBI.Client.Windows.Utilities.UIBlockingAwareExceptionHandler.HandleException(Exception e)
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.Practices.Prism.Commands.DelegateCommandBase.<>c__DisplayClass4_0.<.ctor>b__0(Object arg)
   at Microsoft.Practices.Prism.Commands.DelegateCommandBase.<Execute>d__10.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Practices.Prism.Commands.DelegateCommandBase.Execute(Object parameter)
   at Microsoft.Practices.Prism.Commands.DelegateCommand`1.<Execute>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Practices.Prism.Commands.DelegateCommand`1.Execute(T parameter)
   at Microsoft.PowerBI.Client.Windows.Commands.CompositeCommand`1.Execute(ICommand command, Object parameter)
   at Microsoft.Practices.Prism.Commands.CompositeCommand.Execute(Object parameter)
   at Microsoft.PowerBI.Client.Windows.Commands.CompositeCommand`1.Execute(T parameter)
   at Microsoft.PowerBI.Client.Program.<>c__DisplayClass2_6.<<Main>b__5>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerBI.Client.Program.<>c__DisplayClass2_6.<Main>b__5(MainWindow mainWindow)
   at Microsoft.PowerBI.Client.Windows.MainWindow.<<OnMainWindowInitializationCompleted>b__202_2>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerBI.Client.Windows.MainWindow.<OnMainWindowInitializationCompleted>b__202_2()
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<HandleAwaitableAsyncExceptions>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.HandleAwaitableAsyncExceptions(IExceptionHandler exceptionHandler, Func`1 asyncFunc)
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<HandleAsyncExceptions>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.HandleAsyncExceptions(IExceptionHandler exceptionHandler, Func`1 asyncFunc)
   at Microsoft.PowerBI.Client.Windows.MainWindow.<OnMainWindowInitializationCompleted>b__202_1()
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at Microsoft.Mashup.Client.UI.Shared.WebDialogs.WebDialog.<>n__0(IWindowHandle owner)
   at Microsoft.Mashup.Client.UI.Shared.WindowManager.ShowModal[T](T dialog, Func`1 showModalFunction)
   at Microsoft.PowerBI.Client.Program.<>c__DisplayClass2_0.<Main>b__1()
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<>c__DisplayClass3_0.<HandleExceptionsWithNestedTasks>b__0()
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.PowerBI.Client.Program.Main(String[] args)

Snapshot Trace Logs:
C:\Users\kcarr00\AppData\Local\Microsoft\Power BI Desktop\FrownSnapShot1579504671.zip

Model Default Mode:
Empty

Model Version:
PowerBI_V1

Is Report V3 Models Enabled:
False

Performance Trace Logs:
C:\Users\kcarr00\AppData\Local\Microsoft\Power BI Desktop\PerformanceTraces.zip

Enabled Preview Features:
PBI_showMinervaRibbon
PBI_showMinervaViewNavigator

Disabled Preview Features:
PBI_shapeMapVisualEnabled
PBI_SpanishLinguisticsEnabled
PBI_NewWebTableInference
PBI_qnaLiveConnect
PQ_AIInsightsFunctionBrowser
PBI_realTimeRefresh
PBI_v3Models
PBI_decompositionTree
PBI_themeDialog
PBI_hierarchicalSlicerCreation

Disabled DirectQuery Options:
TreatHanaAsRelationalSource

Cloud:
GlobalCloud

PowerBINonFatalError_MethodDefDescription:
PFE_M_ENGINE_UNKNOWN_ENTITY_REFERENCED

Formulas:

section Section1;

**Comment by kcarr00** [comment]
Please let me know if you need additional info.

**Comment by manuelap-msft** [comment]
Hello,

I'm unable to repro this with the latest .pbit file. Can you make sure you're on the latest version of Power BI Desktop
![image](https://user-images.githubusercontent.com/55705669/96054541-bf679380-0e79-11eb-9385-1aa15f5a2566.png)

As you open the .pbit file, you will be prompted to enter your Org Url - this should be the Environment URL (you can find this in PPAC) of the environment where the CoE Starter Kit is installed. Make sure it's https (not http) when you enter it. You will also need to be logged in to Power BI Desktop with the account that has access to the CoE entities.

If you are using the latest version of the dashboard, you will also need to be on the very latest version of the Core Components solution - the dashboard has a dependency on entities in that solution that might be newer. So if you're on a previous version of Core Components (current is 1.70.3) you will need to upgrade or use a previous version of the dashboard.

Hope that helps,
Manuela

**Comment by kcarr00** [comment]
Hi, this is the version I have installed 
![image](https://user-images.githubusercontent.com/71848708/96265770-7ef83a80-0f8b-11eb-88a5-8e90d1b7eb79.png)

The issue is that the error message is occurring right away as soon as the dashboard is launched.

I am using the latest version of the dashbaord.

What does that error mean? I provided the logs from the error message, can you find out what that means?

**Comment by manuelap-msft** [comment]
Hello,

you're on an old version of Power BI Desktop and will have to upgrade Power BI Desktop to the latest version to use the dashboard. Can you try upgrading Power BI Desktop - you can find the latest version here https://powerbi.microsoft.com/en-us/desktop/

**Comment by NGseb** [comment]
Hello, the october version does not seems to be available to download.
https://powerbi.microsoft.com/en-us/blog/tag/power-bi-desktop/
I have downloaded the latest version https://aka.ms/pbiSingleInstaller and i can see it is still the 2.85.985.0. Where can i find the 2.86 version?
I have also an error when i open the pbit with the latest version of PowerBI : 
![image](https://user-images.githubusercontent.com/16684953/96422126-ee726200-11f7-11eb-99b0-37360936838f.png)
![image](https://user-images.githubusercontent.com/16684953/96422179-ff22d800-11f7-11eb-91df-07831e5e7bd3.png)

**Comment by manuelap-msft** [comment]
Hello,

the 2.86 version is now available
https://www.microsoft.com/en-us/download/details.aspx?id=58494

We will be more mindful of backward compatibility in the future. Please let me know if you're still experiencing issues with the new version!

Thank you

**Comment by manuelap-msft** [comment]
Closing issues with no further action! Please let us know if you continue to experience issues.
