### ISSUE TITLE
[BUG]: 06012021 version of PowerBI Dashboard FAils Object Not Set to an instance of an object

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#674]
**Describe the bug**
06012021 version of PowerBI Dashboard FAils Object Not Set to an instance of an object

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [- PowerBI Dashboard
 - Version [06012021]
 - App or Flow [e.g. Sync Template (v2) - ]PowerBI
**To Reproduce**
Load PowerBI Template in PowerBI DEsktop

**Expected behavior**
I expect the Dashboard to display correctly

**Screenshots**
Feedback Type:
Frown (Error)

Error Message:
Object reference not set to an instance of an object.

Stack Trace:
   at Microsoft.Mashup.Evaluator.ChannelMessenger.CreateChannel()
   at Microsoft.PowerBI.Client.OleDbProvider.PowerBIMashupDataSource.EvaluationSession.Dispose()
   at Microsoft.Mashup.Host.ProviderShared.PackageMashupEvaluator.<>c__DisplayClass7_0.<Evaluate>b__1(Object o)
   at Microsoft.Mashup.Evaluator.Interface.InvokeManyAction`1.CheckDone()
   at Microsoft.Mashup.OleDbProvider.DataHost.MashupEvaluator.<>c__DisplayClass4_1.<Evaluate>b__1()
   at Microsoft.Mashup.OleDbProvider.DataHost.AsyncResultIDataReaderSourceHelper.InvokeThenOnDispose(Action`1 callback, AsyncResult`1 result, Action action)
   at Microsoft.Mashup.OleDbProvider.DataHost.MashupEvaluator.<>c__DisplayClass4_0.<Evaluate>b__0(EvaluationResult2`1 result)
   at Microsoft.Mashup.Evaluator.Interface.EvaluationResultExtensions.InvokeThenOnDispose(Action`1 callback, EvaluationResult2`1 result, Action action)
   at Microsoft.Mashup.Evaluator.Interface.EvaluationResultExtensions.InvokeThenOnDispose[T](Action`1 callback, EvaluationResult2`1 result, Action action)
   at Microsoft.Mashup.Evaluator.LimitedDocumentEvaluatorFactory.Evaluation`1.Complete(EvaluationResult2`1 result)
   at Microsoft.Mashup.Evaluator.LimitedDocumentEvaluatorFactory.Evaluation`1.Cancel()
   at Microsoft.Mashup.Evaluator.Interface.CompositeEvaluation.Cancel()
   at Microsoft.Mashup.Host.ProviderShared.NotifyingMashupEvaluator.MashupEvaluation.Cancel()
   at Microsoft.Mashup.OleDbProvider.MashupCommandEvaluation.AbortIfNotComplete(Boolean timedOut)
   at Microsoft.Mashup.OleDbProvider.MashupCommandEvaluation.Microsoft.OleDb.IDBAsynchStatus.Abort(HCHAPTER hChapter, DBASYNCHOP eOperation)
   at Microsoft.OleDb.Rowset.Abort(HCHAPTER hChapter, DBASYNCHOP eOperation)
   at Microsoft.Mashup.OleDbProvider.TracingRowset.Microsoft.OleDb.IDBAsynchStatus.Abort(HCHAPTER hChapter, DBASYNCHOP eOperation)

Stack Trace Message:
Object reference not set to an instance of an object.

Invocation Stack Trace:
   at Microsoft.Mashup.Host.Document.ExceptionExtensions.GetCurrentInvocationStackTrace()
   at Microsoft.Mashup.Client.UI.Shared.StackTraceInfo..ctor(String exceptionStackTrace, String invocationStackTrace, String exceptionMessage)
   at Microsoft.PowerBI.Client.Windows.Telemetry.PowerBIUserFeedbackServices.GetStackTraceInfo(Exception e)
   at Microsoft.PowerBI.Client.Windows.Telemetry.PowerBIUserFeedbackServices.ReportException(IWindowHandle activeWindow, IUIHost uiHost, FeedbackPackageInfo feedbackPackageInfo, Exception e, Boolean useGDICapture)
   at Microsoft.Mashup.Client.UI.Shared.UnexpectedExceptionHandler.<>c__DisplayClass15_0.<HandleException>b__0()
   at Microsoft.Mashup.Host.Document.SynchronizationContextExtensions.<>c__DisplayClass0_1.<SendAndMarshalExceptions>b__0(Object null)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at Microsoft.Mashup.Client.UI.Windows.DialogWindowBase.ShowModal(IWindowHandle windowHandle)
   at Microsoft.Mashup.Client.UI.Shared.WindowManager.ShowModal[T](T dialog, Func`1 showModalFunction)
   at Microsoft.PowerBI.Client.Windows.FloatingDialog.KoLoadToReportDialog.TryShowDialog(Report report, IExceptionHandler exceptionHandler, IPowerBIWindowService windowService, IQueryServices queryServices, IModelingService modelingService, IUIHost uiHost, LocalizedString title, LoadToModelContext loadToModelContext, IEventAggregationService eventAggregationService)
   at Microsoft.PowerBI.Client.Windows.FloatingDialog.KoLoadToReportDialog.<>c__DisplayClass17_0.<TryShowDialogForQueriesInternal>b__0()
   at Microsoft.PowerBI.Client.Windows.Report.<>c__DisplayClass60_0`1.<SynchronizeLooselyWithQueries>b__0()
   at Microsoft.PowerBI.Client.Windows.Report.<SynchronizeLooselyWithQueriesAsync>d__61`1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerBI.Client.Windows.Report.SynchronizeLooselyWithQueriesAsync[T](Func`1 getTask)
   at Microsoft.PowerBI.Client.Windows.Report.SynchronizeLooselyWithQueries[T](Func`1 action)
   at Microsoft.PowerBI.Client.Windows.Services.TemplateManager.PromptForParametersAndCredentials(IPowerBIWindowService windowService, IQueryServices queryServices, IExceptionHandler exceptionHandler, String filePath, Report templateReport, Boolean allCredentialsSatisfied, Boolean& editQueries)
   at Microsoft.PowerBI.Client.Windows.Services.TemplateManager.TryImportTemplate(IPowerBIWindowService windowService, IQueryServices queryServices, IExceptionHandler exceptionHandler, TelemetryUserActionId entryPoint, Boolean& editQueries, String filePath)
   at Microsoft.PowerBI.Client.Windows.Commands.ApplicationCommands.DataImportCommands.ImportTemplate(IPowerBIWindowService windowService, IExceptionHandler exceptionHandler, ImportTemplateParameters parameters)
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.Practices.Prism.Commands.DelegateCommandBase.<>c__DisplayClass4_0.<.ctor>b__0(Object arg)
   at Microsoft.Practices.Prism.Commands.DelegateCommandBase.<Execute>d__10.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Practices.Prism.Commands.DelegateCommandBase.Execute(Object parameter)
   at Microsoft.Practices.Prism.Commands.DelegateCommand`1.<Execute>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Practices.Prism.Commands.DelegateCommand`1.Execute(T parameter)
   at Microsoft.PowerBI.Client.Windows.Commands.CompositeCommand`1.Execute(ICommand command, Object parameter)
   at Microsoft.Practices.Prism.Commands.CompositeCommand.Execute(Object parameter)
   at Microsoft.PowerBI.Client.Windows.Commands.CompositeCommand`1.Execute(T parameter)
   at Microsoft.PowerBI.Client.Program.<>c__DisplayClass4_7.<<Main>b__8>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerBI.Client.Program.<>c__DisplayClass4_7.<Main>b__8(MainWindow mainWindow)
   at Microsoft.PowerBI.Client.Windows.MainWindow.<<ActivateMainWindow>b__114_1>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerBI.Client.Windows.MainWindow.<ActivateMainWindow>b__114_1()
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<HandleAwaitableAsyncExceptions>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.HandleAwaitableAsyncExceptions(IExceptionHandler exceptionHandler, Func`1 asyncFunc)
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<HandleAsyncExceptions>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.HandleAsyncExceptions(IExceptionHandler exceptionHandler, Func`1 asyncFunc)
   at Microsoft.PowerBI.Client.Windows.MainWindow.<ActivateMainWindow>b__114_0()
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at Microsoft.Mashup.Client.UI.Shared.WindowManager.ShowModal[T](T dialog, Func`1 showModalFunction)
   at Microsoft.PowerBI.Client.Program.<>c__DisplayClass4_0.<Main>b__1()
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<>c__DisplayClass3_0.<HandleExceptionsWithNestedTasks>b__0()
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.PowerBI.Client.Program.Main(String[] args)

PowerBINonFatalError:
{"AppName":"PBIDesktop","AppVersion":"2.88.702.0","ModuleName":"","Component":"Microsoft.Mashup.Evaluator.ChannelMessenger","Error":"Microsoft.Mashup.Host.Document.SerializedException - System.NullReferenceException","MethodDef":"CreateChannel","ErrorOffset":""}

Snapshot Trace Logs:
C:\xxxxxx\xxxxx\AppData\Local\Microsoft\Power BI Desktop\FrownSnapShote67d2b2c-bfd0-4cba-bada-a4ae9a5f3fcd.zip

Model Default Mode:
Empty

Model Version:
PowerBI_V1

Is Report V3 Models Enabled:
True

Performance Trace Logs:
C:\Uxxxxxx\xxxxxx\AppData\Local\Microsoft\Power BI Desktop\PerformanceTraces.zip

Enabled Preview Features:
PBI_NewWebTableInference
PBI_v3ModelsPreview

Disabled Preview Features:
PBI_shapeMapVisualEnabled
PBI_SpanishLinguisticsEnabled
PBI_JsonTableInference
PBI_ImportTextByExample
PBI_ExcelTableInference
PBI_qnaLiveConnect
PBI_eimInformationProtectionForDesktop
PBI_azureMapVisual
PBI_dataPointLassoSelect
PBI_compositeModelsOverAS
PBI_narrativeTextBox
PBI_dynamicParameters
PBI_anomalyDetection
PBI_newFieldList
PBI_cartesianMultiplesAuthoring

Disabled DirectQuery Options:
TreatHanaAsRelationalSource

Cloud:
GlobalCloud

PowerBINonFatalError_ErrorDescription:
System.NullReferenceException

PowerBIUserFeedbackServices_IsReported:
True

Formulas:

section Section1;

**Additional context**

**Comment by manuelap-msft** [comment]
I'm assuming this is the error message you are seeing
![image](https://user-images.githubusercontent.com/55705669/103881078-df51d080-50d1-11eb-9ef5-534d589a9dda.png)

If so, can you please click Close on the Error and wait for the Refresh in the background to fail - you might have to hit close or cancel multiple times. It will say something like:

**OrgUrl**
Load was cancelled by an error in loading a previous table.
**Environment**
Load was cancelled by an error in loading a previous table.

Please copy the whole Refresh failure here, so I can see which previous table is failing. 

As long as the Power BI Stack trace it, unfortunately it doesn't tell me what part of the data is causing the issue - only the Load error will tell me that. Likely there's something in your data that is causing the issue, which we can't repo in our dev environment.

**Comment by NPrice99** [comment]
OrgUrl
Load was cancelled by an error in loading a previous table.
Environment
Load was cancelled by an error in loading a previous table.
App
Load was cancelled by an error in loading a previous table.
Flow
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Maker
USERELATIONSHIP function can only use the two columns references participating in relationship. Column 'admin_displayname' in Table 'Maker' contains a duplicate value 'xxxxxxxxxxxxxxServiceAccount' and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table.
App Connection Reference
Load was cancelled by an error in loading a previous table.
Flow Connection Reference
Load was cancelled by an error in loading a previous table.
Audit Log
The following syntax error occurred during parsing: Invalid token, Line 1, Offset 1, 'audi ). OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Connector
Load was cancelled by an error in loading a previous table.
Flow Action Details
Load was cancelled by an error in loading a previous table.
NonProdWords
Load was cancelled by an error in loading a previous table.
CoE Settings
Load was cancelled by an error in loading a previous table.
Virtual Agent
Load was cancelled by an error in loading a previous table.
Virtual Agent Component
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Virtual Agent Flows
Load was cancelled by an error in loading a previous table.
Virtual Agent Makers
Load was cancelled by an error in loading a previous table.
RPA
Load was cancelled by an error in loading a previous table.
RPA Sessions
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Environment Maker
Load was cancelled by an error in loading a previous table.
Date Last Refreshed
Load was cancelled by an error in loading a previous table.


Works OK with template version of 24/11

**Comment by manuelap-msft** [comment]
Can you please try this version:

https://github.com/microsoft/powerapps-tools/raw/master/Administration/CoEStarterKit/Individual%20Components/Dashboard-PowerPlatformAdminDashboard-2021-01-07.pbit

**Comment by NPrice99** [comment]
OrgUrl
Load was cancelled by an error in loading a previous table.
Environment
OLE DB or ODBC error: Object reference not set to an instance of an object..
App
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Flow
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Maker
Column 'admin_displayname' in Table 'Maker' contains a duplicate value 'xxxxxxxxxxxxxCIServiceAccount' and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table.
App Connection Reference
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Flow Connection Reference
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Audit Log
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Connector
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Flow Action Details
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
NonProdWords
Load was cancelled by an error in loading a previous table.
CoE Settings
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Virtual Agent
Load was cancelled by an error in loading a previous table.
Virtual Agent Component
OLE DB or ODBC error: Object reference not set to an instance of an object..
Virtual Agent Flows
OLE DB or ODBC error: Object reference not set to an instance of an object..
Virtual Agent Makers
Column 'admin_displayname' in Table 'Virtual Agent Makers' contains a duplicate value 'xxxxxxxxxxCIServiceAccount' and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table.
RPA
Load was cancelled by an error in loading a previous table.
RPA Sessions
OLE DB or ODBC error: Object reference not set to an instance of an object..
Environment Maker
Load was cancelled by an error in loading a previous table.
Date Last Refreshed
Load was cancelled by an error in loading a previous table.

**Comment by manuelap-msft** [comment]
Sorry, looks like I missed one more place where the maker name was expected to be unique - can you try this one?
https://github.com/microsoft/powerapps-tools/raw/master/Administration/CoEStarterKit/Individual%20Components/Dashboard-PowerPlatformAdminDashboard-2021-01-07.pbit

Thank you for your help in testing this!

**Comment by NPrice99** [comment]
Hi Manuela 

That one worked !

Warrington is now being displayed in the UK.

Thanks for sorting this out.

Regards

Nigel

**Comment by manuelap-msft** [comment]
Awesome, thank you for the speedy help with testing - it was something I could not repo in my dev environment! I will make this part of the main release now.

**Comment by marchantrr** [comment]
> Sorry, looks like I missed one more place where the maker name was expected to be unique - can you try this one?
> https://github.com/microsoft/powerapps-tools/raw/master/Administration/CoEStarterKit/Individual%20Components/Dashboard-PowerPlatformAdminDashboard-2021-01-07.pbit
> 
> Thank you for your help in testing this!

Can someone share a link to the Dashboard-PowerPlatformAdminDashboard-2021-01-07.pbit file again?  The link reference here is no longer valid and the newer file with the TDS endpoint isn't working for me because our audit log table is too large.

**Comment by manuelap-msft** [comment]
Here is the latest version using Import: https://github.com/microsoft/powerapps-tools/blob/master/Administration/CoEStarterKit/Individual%20Components/Dashboard-PowerPlatformAdminDashboard-2021-02-02%20(1).pbit
